structure(list(url = "https://accounts.spotify.com/api/token", 
    status_code = 400L, headers = structure(list(date = "Mon, 06 May 2024 16:32:55 GMT", 
        `content-type` = "application/json", `sp-trace-id` = "2caf6e69a92b87c3", 
        `x-envoy-upstream-service-time` = "5", server = "envoy", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `content-encoding` = "gzip", vary = "Accept-Encoding", 
        via = "HTTP/2 edgeproxy, 1.1 google", `alt-svc` = "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(date = "Mon, 06 May 2024 16:32:55 GMT", 
            `content-type` = "application/json", `sp-trace-id` = "2caf6e69a92b87c3", 
            `x-envoy-upstream-service-time` = "5", server = "envoy", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `content-encoding` = "gzip", 
            vary = "Accept-Encoding", via = "HTTP/2 edgeproxy, 1.1 google", 
            `alt-svc` = "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_accounts.spotify.com", 
    ".accounts.spotify.com"), flag = c(FALSE, TRUE), path = c("/", 
    "/"), secure = c(TRUE, TRUE), expiration = structure(c(3861975508, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("__Host-device_id", 
    "sp_tr"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"error\":\"invalid_client\",\"error_description\":\"Invalid client\"}"), 
    date = structure(1715013175, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.5e-05, 
    connect = 5.5e-05, pretransfer = 0.000253, starttransfer = 0.055483, 
    total = 0.055565)), class = "response")
